name: cards
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch::pytorch=2.2.0
  - numpy=1.24.3
  - pip=23.3
  - pip:
    - transformers==4.38.0
    - datasets>=2.14.0
    - tqdm>=4.65.0
    - scikit-learn>=1.3.0
    - accelerate>=0.26.0
    - openai>=1.0.0
    - python-dotenv>=1.0.0
    - sentencepiece>=0.1.99
    - protobuf>=3.20.0
    - matplotlib>=3.7.0
    - seaborn>=0.12.0
    - scipy>=1.10.0
    - umap-learn>=0.5.0  # Optional, for UMAP visualization
